version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service

  discount-service:
    build: ./discount-service
    container_name: discount-service

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8002:8000"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000
      - DISCOUNT_SERVICE_URL=http://discount-service:8000
    depends_on:
      - product-service
      - discount-service